{ADC_RefHigh_volt: 30, ADC_RefHigh_curr: 7, ADC_RefLow_volt: 1, ADC_RefLow_curr: 7, DiffBn_coarse: 3, DiffBn_fine: 88, OFFBn_coarse: 1, OFFBn_fine: 91, ONBn_coarse: 6,
  ONBn_fine: 78, PrBp_coarse: 3, PrBp_fine: 58, PrSFBp_coarse: 2, PrSFBp_fine: 16,
  RefrBp_coarse: 3, RefrBp_fine: 27, aps_enabled: true, dvs_enabled: true, exposure: 40000,
  frame_delay: 0, imu_acc_scale: 3, imu_enabled: true, imu_gyro_scale: 3, max_events: 0,
  streaming_rate: 30}

